### PR TITLE
fix(c): update queries from upstream

### PR DESCRIPTION
**Pull request by amaanq**
C will update & break sometime later today, but it now has a visible else_clause rule!

### CODE REVIEW

**Comment by andymass** [comment]
Does this fix https://github.com/andymass/vim-matchup/issues/310?

**Comment by amaanq** [comment]
yes

**Comment by andymass** [comment]
Got it, I appreciate it!

**Comment by lucario387** [comment]
@andymass nvim-treesitter has updated and will break this, bumping this to notify

**Comment by amaanq** [comment]
yeah this can be merged now

**Comment by andymass** [comment]
thanks!

**Comment by lucario387** [comment]
Thank you for the quick fix 🙇‍♂️

**Pull request merged**
