### PR TITLE
Allow b:matchup_delim_enabled to be set in other scripts.

### PR DESCRIPTION
**Pull request by phmarek**

### CODE REVIEW

**Comment by andymass** [comment]
Hi @phmarek , what is the context for this?  b:matchup_delim_enabled is an internal variable to the plugin, why do you want to change it?

**Comment by phmarek** [comment]
I've got a plugin that writes a REPL buffer; depending on the calculation in the other process there might be several hundred (or more) writes to the buffer in a very short time.

The `TextChanged` event causes nvim (via MatchUp) to use quite a lot of CPU (measured with nvim's `:profile`); as the REPL buffer shows _results_ and not the code that's used for calculation, the delimiter matching isn't important (for me), and so I turn it off for that buffer.

When the buffer is created, I can set the `b:matchup_delim_enabled` variable; but then it must not be overriden by `BufLoad` events, and the order of events isn't well-defined, so I put the `if` there.

In the end, this variable becomes an easy way to improve nvim's performance on such buffers.

**Comment by andymass** [comment]
Thanks, that helps a lot.  I just wanted to offer an alternative which is already supported: 

    let [b:matchup_matchparen_enabled, b:matchup_matchparen_fallback] = [0, 0]

Does this work in your use-case?  Or is b:matchup_delim_enabled doing something different?  Granted, my solution is more cumbersome but this shouldn't matter for non-interactive use.

**Comment by phmarek** [comment]
Even
```
let b:matchup_matchparen_enabled = 0
```
is sufficient - and the fallback isn't performance prohibitive as the cursor is typically in an empty line by itself.

Hmmm, I was sure I grepped for `b:.*enabled`, why didn't I see that one?

Thanks!

**Pull request closed without merging**
