### PR TITLE
update nvim 0.7 treesitter api

### LINKED ISSUE #215: Use new treesitter API
### Explain the issue

`nvim-treesitter` has recently deprecated the `ts_utils.get_node_text()` function in favor of this now being a built in part of neovim's treesitter API (https://github.com/nvim-treesitter/nvim-treesitter/commit/c3848e713a8272e524a7eabe9eb0897cf2d6932e). This should be able to be resolved by adding the local variable

```lua
local ts_query = vim.treesitter.query
```

and replacing all `ts_utils.get_node_text(...)` with `ts_query.get_node_text(...)` in the `lua/treesitter-matchup/internal.lua` file.

Most issues are related to bugs or problems. In these cases, you should
include a minimal working example and a minimal vimrc file (see below), as
well as:

1. What vim version are you using?  Neovim v0.7
   tree-sitter or classic matching? tree-sitter
2. Steps to reproduce

  - Install any treesitter parsers
  - Install vim-matchup and enable treesitter matching
  - Open any file with treesitter

3. Expected behavior

  - No errors/working

4. Observed behavior

  - `vim-matchup` throws errors that function doesn't exist because it has been deprecated

### PR DESCRIPTION
**Pull request by mehalter**
Resolve #215

### CODE REVIEW

**Comment by andymass** [comment]
Thanks @mehalter!  I tried this and it causes an error for me (nvim 0.6.1).
Can I assume this patch will only work on v0.7?
To what extent should we be supporting older neovim versions, is it acceptable to users to require 0.7?

**Comment by mehalter** [comment]
This is a good question. It will no longer work in v0.6.1. Given other major plugins no longer support pre v0.7 I think it's safe to assume. Right now `nvim-treesitter` only supports v0.7+ now since it is using this new built in API and dropped the deprecated pre-v0.7 API.

Also I am doing some more testing and I don't think that this is a simple drop in fix as I thought it was. I will need to investigate more before this gets merged

**Comment by megalithic** [comment]
nvim-lspconfig is fixing to require 0.7 if you want updates...

https://www.reddit.com/r/neovim/comments/u5si2w/breaking_changes_inbound_next_few_weeks_for/

Sounds like treesitter and lsp plugin authors will be in a pickle if they want to support future neovim features.

**Comment by andymass** [comment]
Thanks @mehalter and @megalithic.  It sounds like if nvim-treesitter itself only supports 0.7 and this plugin (tree sitter component only) is still a kind of sub-plugin to nvim-treesitter, we have no real choice right now but to force the upgrade.  (Along with being the apparent standard practice among major neovim plugins.)

OK @mehalter, will await a further patch before merging.  I really appreciate the help here.

**Comment by megalithic** [comment]
More treesitter-based plugins are afflicted by this update for 0.7: 

https://github.com/SmiteshP/nvim-gps/issues/89

**Comment by mehalter** [comment]
@andymass I think I have resolved the issue now :) seems to be all in working order. It looks like the built in API will return just a string if there is only one match so we don't have to index into it with `[1]` every time.

**Comment by andymass** [comment]
Thanks mehalter@ for the update!   Merging (without testing).  If anyone has issues they will need to upgrade neovim or pin the version of this plugin.

**Pull request merged**
